#!/usr/bin/env python3
"""
codex-image-import.py — import PNGs generated by OpenAI Codex CLI's built-in
gpt-image-2 tool into this fork, gated by scan_assets.py and PROVENANCE.

Codex CLI v0.130 (May 2026) writes generated images to
$CODEX_HOME/generated_images/<session-id>/ig_<hash>.png. This script
recurses into the session subdirectories, picks the most recent PNG,
runs a chunk-strip step that removes non-whitelist chunks (notably the
C2PA `caBX` JUMBF block that gpt-image-2 auto-injects), re-scans the
cleaned PNG with scan_assets.py, and only on a clean pass moves it into
assets/<brand>-brand/generated/<name>.png with a PROVENANCE entry.

Strip policy (added 2026-05-09 after live validation):
- Allowed PNG chunks come from scripts/scan_assets.py PNG_WHITELIST —
  single source of truth so the strip stays in sync with the scan.
- Stripped chunk names land in PROVENANCE so the audit trail is honest
  about what was removed. The "AI provenance" replacement is the
  PROVENANCE.md entry itself (Source: codex-cli + prompt hash + session).
- Threats that survive a strip (trailing bytes after IEND, missing
  signature, oversized text in a whitelisted chunk) still trigger
  hard-fail because scan_assets.py runs on the stripped output.

Usage:
    python3 scripts/codex-image-import.py \\
        --brand dji \\
        --name pocket4-hero \\
        --prompt "matte black DJI Pocket 4 floating on charcoal background, editorial lighting, no text" \\
        --codex-session 0193f9aa-... \\
        --assets-root assets

    # Pick the most recent file from $CODEX_HOME/generated_images/:
    python3 scripts/codex-image-import.py --brand dji --name foo --prompt "..."

    # Specify the source PNG explicitly:
    python3 scripts/codex-image-import.py --brand dji --name foo --prompt "..." \\
        --src ~/.codex/generated_images/2026-05-09T12-33-01.png

    # Dry-run (validate gate but do not move):
    python3 scripts/codex-image-import.py --brand dji --name foo --prompt "..." --dry-run

Exit codes:
    0  imported (or dry-run validated)
    2  scan_assets WARN — import blocked
    3  scan_assets CRITICAL — import blocked
    4  prompt confidentiality violation (codename pattern detected)
    1  CLI / IO error (no PNG found, missing brand, write failure)

Stdlib only. No external dependencies. Delegates to scripts/scan_assets.py
via subprocess so the scanner stays the single source of truth on chunk
policy.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import os
import re
import shutil
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_SCAN_ASSETS = _HERE / "scan_assets.py"
_PNG_SIGNATURE = b"\x89PNG\r\n\x1a\n"


def _load_scan_assets_whitelist() -> frozenset[str]:
    """Import scan_assets.py's PNG_WHITELIST so the strip stays in sync.

    scan_assets.py uses underscores so it's importable directly. Fall back
    to a hard-coded mirror only if the import fails (defensive — should
    never trip in normal use).
    """
    try:
        sys.path.insert(0, str(_HERE))
        import scan_assets  # type: ignore
        return frozenset(scan_assets.PNG_WHITELIST)
    except Exception:
        # Mirror of scan_assets.py PNG_WHITELIST — keep in sync manually if
        # the import fails. Tests assert the two sets stay equal.
        return frozenset({
            "IHDR", "PLTE", "IDAT", "IEND",
            "tRNS", "cHRM", "gAMA", "iCCP", "sBIT", "sRGB",
            "iTXt", "tEXt", "zTXt",
            "bKGD", "hIST", "pHYs", "sPLT", "tIME",
            "acTL", "fcTL", "fdAT",
            "eXIf",
        })
    finally:
        if str(_HERE) in sys.path:
            sys.path.remove(str(_HERE))


PNG_WHITELIST = _load_scan_assets_whitelist()

# Default codename patterns blocked from being sent to Codex CLI.
# Real list lives in references/security-config.md §1.5; this is a
# minimal regex-set so the script is self-contained for tests.
DEFAULT_CODENAME_PATTERNS = (
    re.compile(r"\bproject[-_ ]?[a-z]{4,}\b", re.IGNORECASE),  # "project Falcon"
    re.compile(r"\b(internal|nda|confidential)[-_ ][a-z]+", re.IGNORECASE),
)

PROMPT_PREVIEW_LIMIT = 300


# ---------------------------------------------------------------------------
# Confidentiality gate — runs before any Codex interaction
# ---------------------------------------------------------------------------

def check_prompt_confidentiality(prompt: str, extra_patterns: list[re.Pattern] | None = None) -> list[str]:
    """Return a list of matched codename strings. Empty list = clean."""
    matches: list[str] = []
    patterns = list(DEFAULT_CODENAME_PATTERNS) + (extra_patterns or [])
    for pat in patterns:
        for m in pat.finditer(prompt):
            matches.append(m.group(0))
    return matches


# ---------------------------------------------------------------------------
# Source PNG discovery
# ---------------------------------------------------------------------------

def codex_home() -> Path:
    return Path(os.environ.get("CODEX_HOME") or (Path.home() / ".codex"))


def discover_latest_png(generated_dir: Path) -> Path | None:
    """Pick the most recently modified .png anywhere under the codex generated dir.

    Codex CLI v0.130 (2026) writes images to
    `~/.codex/generated_images/<session-id>/ig_<hash>.png`, not directly into
    the parent directory. Recursive glob handles both layouts (flat
    pre-0.115 layout and the per-session subdirectory layout used today).
    """
    if not generated_dir.is_dir():
        return None
    pngs = sorted(
        generated_dir.rglob("*.png"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return pngs[0] if pngs else None


# ---------------------------------------------------------------------------
# Stego-resistant chunk scan via scan_assets.py
# ---------------------------------------------------------------------------

def run_scan(src: Path) -> tuple[int, str]:
    """Returns (exit_code, captured_output). exit 0 = pass."""
    if not _SCAN_ASSETS.is_file():
        return 1, f"scan_assets.py not found at {_SCAN_ASSETS}"
    result = subprocess.run(
        [sys.executable, str(_SCAN_ASSETS), "--file", str(src)],
        capture_output=True,
        text=True,
        check=False,
    )
    return result.returncode, (result.stdout + result.stderr).strip()


# ---------------------------------------------------------------------------
# PNG chunk strip — drops non-whitelist chunks before the scan + import
# ---------------------------------------------------------------------------

def strip_png_to_whitelist(data: bytes) -> tuple[bytes, list[tuple[str, int]]]:
    """Parse PNG chunks, keep only those whose tag is in PNG_WHITELIST.

    Returns (cleaned_bytes, dropped) where dropped is a list of
    (chunk_tag, chunk_length) tuples — recorded in PROVENANCE so the
    audit trail is explicit about what disappeared.

    Behavior on malformed input:
    - Missing PNG signature → return data unchanged + dropped=[]; the
      subsequent scan_assets call will mark this as CRITICAL.
    - Truncated chunk → stop parsing at the truncation point. The result
      is whatever could be cleanly parsed; the original anomaly is
      surfaced by the post-strip scan, not silently swallowed here.
    - Trailing bytes after IEND → already not copied (we stop after
      the IEND chunk we emit), so the strip implicitly fixes this.
      But trailing bytes still need to be reported, so we don't dedupe
      them here — the post-strip scan will be clean and the pre-strip
      audit captures the original CRITICAL via the source file hash.
    """
    if not data.startswith(_PNG_SIGNATURE):
        return data, []

    out = bytearray(_PNG_SIGNATURE)
    dropped: list[tuple[str, int]] = []
    pos = len(_PNG_SIGNATURE)
    saw_iend = False

    while pos + 8 <= len(data):
        length = int.from_bytes(data[pos:pos + 4], "big")
        tag_bytes = data[pos + 4:pos + 8]
        try:
            tag = tag_bytes.decode("ascii")
        except UnicodeDecodeError:
            # Garbage tag — treat the rest as untrusted, stop here.
            break

        chunk_end = pos + 8 + length + 4  # length + tag + data + crc
        if chunk_end > len(data):
            # Truncated — abandon. Already-emitted output stops at the
            # last clean chunk; scan_assets will catch the truncation.
            break

        chunk_full = data[pos:chunk_end]
        if tag in PNG_WHITELIST:
            out.extend(chunk_full)
            if tag == "IEND":
                saw_iend = True
                # Record any trailing bytes after IEND as a synthetic dropped
                # entry so the audit trail is honest about what disappeared.
                trailing = len(data) - chunk_end
                if trailing > 0:
                    dropped.append(("__TRAIL__", trailing))
                break
        else:
            dropped.append((tag, length))

        pos = chunk_end

    # If the input lacked an IEND we keep what we have; the post-strip
    # scan will detect the missing terminator (or the truncation).
    return bytes(out), dropped


# ---------------------------------------------------------------------------
# PROVENANCE writer
# ---------------------------------------------------------------------------

def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def append_provenance(
    report: Path,
    *,
    src_name: str,
    dst_rel: str,
    prompt: str,
    codex_session: str | None,
    src_hash: str,
    dst_hash: str | None,
    scan_exit: int,
    scan_output: str,
    blocked: bool,
    stripped_chunks: list[tuple[str, int]] | None = None,
) -> None:
    report.parent.mkdir(parents=True, exist_ok=True)
    if not report.exists():
        report.write_text(
            "# Asset PROVENANCE\n\n"
            "Audit trail for every external asset brought into this project. "
            "Maintained by `scripts/svg-sanitize.py` and `scripts/codex-image-import.py`.\n\n",
            encoding="utf-8",
        )

    section = io.StringIO()
    arrow = "BLOCKED" if blocked else "imported"
    section.write(f"\n## generated/{dst_rel} ({arrow})\n")
    section.write(f"- Date: {datetime.now(timezone.utc).date().isoformat()}\n")
    section.write("- Source: codex-cli (gpt-image-2 via Codex CLI, OpenAI)\n")
    section.write(f"- Source file: `{src_name}`\n")
    if codex_session:
        section.write(f"- Codex session: `{codex_session}`\n")
    preview = prompt[:PROMPT_PREVIEW_LIMIT]
    if len(prompt) > PROMPT_PREVIEW_LIMIT:
        preview += "…"
    section.write(f"- Prompt: {preview}\n")
    section.write(f"- Prompt SHA-256: `{sha256_bytes(prompt.encode('utf-8'))}`\n")
    section.write(f"- Source SHA-256: `{src_hash}`\n")
    if dst_hash:
        section.write(f"- Output SHA-256: `{dst_hash}`\n")
    if stripped_chunks:
        def _label(tag: str, length: int) -> str:
            if tag == "__TRAIL__":
                return f"trailing-bytes({length}B)"
            return f"{tag}({length}B)"
        chunk_summary = ", ".join(_label(t, l) for t, l in stripped_chunks)
        section.write(f"- Stripped chunks: {chunk_summary}\n")
        section.write(
            "- AI provenance: replaced upstream C2PA metadata with this PROVENANCE entry "
            "(Source line above identifies the generator)\n"
        )
    if scan_exit == 0:
        section.write("- Stego scan (post-strip): PASS\n")
    else:
        # Inline first line of the scan output for the audit trail
        first_line = scan_output.splitlines()[0] if scan_output else "(no output)"
        section.write(
            f"- Stego scan (post-strip): BLOCKED (scan_assets exit {scan_exit}) — {first_line}\n"
        )
    section.write(f"- Status: {'BLOCKED — not imported' if blocked else 'imported'}\n")

    with report.open("a", encoding="utf-8") as fh:
        fh.write(section.getvalue())


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument("--brand", required=True, help="brand name — target dir is assets/<brand>-brand/generated/")
    ap.add_argument("--name", required=True, help="output asset name (without .png)")
    ap.add_argument("--prompt", required=True, help="prompt that produced the image (recorded in PROVENANCE)")
    ap.add_argument("--src", help="explicit source PNG (default: latest .png in $CODEX_HOME/generated_images/)")
    ap.add_argument("--codex-session", default=None, help="Codex session id, recorded in PROVENANCE")
    ap.add_argument("--assets-root", default="assets", help="repo assets directory (default: ./assets)")
    ap.add_argument("--codex-home", default=None, help="override $CODEX_HOME")
    ap.add_argument("--dry-run", action="store_true", help="run gate, do not move file")
    args = ap.parse_args(argv)

    # 1. Confidentiality gate
    matches = check_prompt_confidentiality(args.prompt)
    if matches:
        sys.stderr.write(
            "ERROR: prompt contains potentially confidential codename(s): "
            f"{matches}\n"
            "Refusing to send to external Codex CLI. Rephrase or remove the codename "
            "and re-run. See references/security-config.md §1.5.\n"
        )
        return 4

    # 2. Locate source PNG
    if args.src:
        src = Path(args.src).expanduser()
    else:
        gen_dir = (
            Path(args.codex_home).expanduser() / "generated_images"
            if args.codex_home
            else codex_home() / "generated_images"
        )
        src = discover_latest_png(gen_dir)
        if src is None:
            sys.stderr.write(
                f"ERROR: no .png found in {gen_dir}. "
                "Has Codex generated an image yet?\n"
            )
            return 1

    if not src.is_file():
        sys.stderr.write(f"ERROR: source PNG not found: {src}\n")
        return 1

    src_bytes = src.read_bytes()
    src_hash = sha256_bytes(src_bytes)

    dst_dir = Path(args.assets_root) / f"{args.brand}-brand" / "generated"
    dst_rel = f"{args.name}.png"
    dst = dst_dir / dst_rel
    report = Path(args.assets_root) / f"{args.brand}-brand" / "PROVENANCE.md"

    # 3. Strip non-whitelist chunks (caBX / C2PA / etc) BEFORE scanning.
    #    The strip never adds bytes, so threats that survive (truncation,
    #    missing signature, oversized text in a whitelisted chunk) still
    #    surface to scan_assets in step 4.
    stripped_bytes, stripped_chunks = strip_png_to_whitelist(src_bytes)

    # 4. Re-scan the stripped output. Write to a temp file inside
    #    the destination dir's parent so subprocess sees a real path.
    tmp_dir = Path(args.assets_root) / f"{args.brand}-brand"
    tmp_dir.mkdir(parents=True, exist_ok=True)
    tmp_scan = tmp_dir / f".{args.name}.scanning.png"
    tmp_scan.write_bytes(stripped_bytes)
    try:
        scan_exit, scan_output = run_scan(tmp_scan)
    finally:
        try:
            tmp_scan.unlink()
        except OSError:
            pass

    if scan_exit != 0:
        # Hard-fail: do NOT move. Record BLOCKED + the strip attempt in PROVENANCE.
        append_provenance(
            report,
            src_name=src.name,
            dst_rel=dst_rel,
            prompt=args.prompt,
            codex_session=args.codex_session,
            src_hash=src_hash,
            dst_hash=None,
            scan_exit=scan_exit,
            scan_output=scan_output,
            blocked=True,
            stripped_chunks=stripped_chunks,
        )
        sys.stderr.write(
            f"BLOCKED: scan_assets.py exited {scan_exit} on stripped PNG. Not imported.\n"
            f"  Source: {src}\n"
            f"  Stripped: {len(stripped_chunks)} chunk(s) — strip alone wasn't enough\n"
            f"  PROVENANCE entry written to: {report}\n\n"
            f"--- scan_assets output ---\n{scan_output}\n"
        )
        return scan_exit  # propagate 2 (WARN) or 3 (CRITICAL)

    # 5. Import — atomic move of the stripped bytes
    if args.dry_run:
        print(
            f"DRY-RUN: would write stripped PNG to {dst} "
            f"(stripped {len(stripped_chunks)} chunk(s))"
        )
        return 0

    dst_dir.mkdir(parents=True, exist_ok=True)
    if dst.exists():
        sys.stderr.write(f"ERROR: destination already exists: {dst}\n")
        return 1

    # Write to a temp file in the same directory then rename — atomic on POSIX
    tmp = dst.with_suffix(".png.tmp")
    tmp.write_bytes(stripped_bytes)
    os.rename(tmp, dst)

    dst_hash = sha256_bytes(stripped_bytes)

    append_provenance(
        report,
        src_name=src.name,
        dst_rel=dst_rel,
        prompt=args.prompt,
        codex_session=args.codex_session,
        src_hash=src_hash,
        dst_hash=dst_hash,
        scan_exit=0,
        scan_output="",
        blocked=False,
        stripped_chunks=stripped_chunks,
    )

    # Remove the codex-side source so the same PNG is not re-imported next run
    try:
        src.unlink()
    except OSError:
        pass

    if stripped_chunks:
        def _slabel(tag: str, length: int) -> str:
            if tag == "__TRAIL__":
                return f"trailing-bytes({length}B)"
            return f"{tag}({length}B)"
        chunks_str = ", ".join(_slabel(t, l) for t, l in stripped_chunks)
        print(f"✓ imported (stripped {chunks_str}): {src.name} → {dst}")
    else:
        print(f"✓ imported: {src.name} → {dst}")
    print(f"  PROVENANCE: {report}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
